### ISSUE TITLE
My mine wont fill.

### ISSUE THREAD

**Issue by DarkFeline99** [JamieS1211/MineReset#6]
Hi i just started using your plugin this afternoon. thought i set it up correctly but when i go to manually fill the mine with the /mine fill command it gives me an error msg in the console. was wondering if u could tell whats wrong with it. i will attach my mine config file and paste the error msg. Sorry for the long post, i dont know how to get this error msg to you otherwise...

[20-07-2018 22:36:59] [Sponge]: The Scheduler tried to run the task MineFillingAsyncJobs owned by Plugin{id=minereset, name=MineReset, version=1.0.12(API6), description=Resets mines, url=http://pixelmonweb.officialtjp.com, authors=[JamieS1211], source=/home/smpicnic/server/data/mods/MineReset-1.0.12.API6.jar}, but an error occured.
[20-07-2018 22:36:59] java.lang.NoClassDefFoundError: org/spongepowered/api/event/cause/NamedCause
[20-07-2018 22:36:59] at com.github.jamies1211.minereset.Actions.FillMineAction.lambda$fill$3(FillMineAction.java:40) ~[FillMineAction.class:?]
[20-07-2018 22:36:59] at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139) ~[Task$Builder.class:1.12.2-2611-7.1.0-BETA-3002]
[20-07-2018 22:36:59] at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:186) ~[SchedulerBase.class:1.12.2-2611-7.1.0-BETA-3002]
[20-07-2018 22:36:59] at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_65]
[20-07-2018 22:36:59] at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_65]
[20-07-2018 22:36:59] at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_65]
[20-07-2018 22:36:59] at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_65]
[20-07-2018 22:36:59] at java.lang.Thread.run(Unknown Source) [?:1.8.0_65]
[20-07-2018 22:36:59] Caused by: java.lang.ClassNotFoundException: org.spongepowered.api.event.cause.NamedCause
[20-07-2018 22:36:59] at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
[20-07-2018 22:36:59] at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_65]
[20-07-2018 22:36:59] at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_65]
[20-07-2018 22:36:59] ... 8 more
[20-07-2018 22:36:59] Caused by: java.lang.NullPointerException

[general.txt](https://github.com/JamieS1211/MineReset/files/2215898/general.txt)

**Comment by JamieS1211** [comment]
It seems that you are using the wrong version of the plugin for your sponge version. The sponge change from API 6 to API 7 chamged the "named cause" hence the reason you get a no class found error. At the moment you are using the mine reset version specifically for API 6, you should be using the normal version (MineReset1.0.12.jar). If you could change out the jar files and let me know if its all working for you so i can close this issue.
